### ISSUE TITLE
Activity Tracker

### ISSUE THREAD

**Issue by dharma-guardian** [secure-software-engineering/rose#102]
Come up with a measure to record or infer when the user is engaging in passive interaction, such as scrolling down news feed, browsing, etc. This is an interesting and valid way of engage in FB without triggering any active interactions (e.g., comment, like)

Proposed Solution
- [x] scroll distance in px
- [x] is Facebook on top of all tabs/windows at certain intervall
- [x] amount of mouse clicks
- [x] mouse movement distance
- [x] login status

Then everything saved in Intervall switch timecode

**Comment by dharma-guardian** [comment]
Proposed Solution
- height scrolled in px
- is facebook on top of all windows at a certain intervall
- mouse clicks

**Comment by dharma-guardian** [comment]
The store interval should be configurable in ROSE.

**Comment by dharma-guardian** [comment]
http://jsbin.com/yoqapafecu/1/edit?js,output
