### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by apoller** [secure-software-engineering/rose#56]
Please check the following things (if applicable) before finalizing Release

General:
- [x] README names used libraries
- [x] Build scripts up to date
- [x] all text multilingual (DE/EN)

Repository
- [x] temporary and widowed files removed
- [x] all source code checked in
- [x] observers / extractors are up-to-date in default configuration

Source code
- [x] removed unreached abandoned source code
- [x] remove obsolete dependencies/packages
- [x] every source code file contains GPL-header and copyright information
- [x] source code comments complete

Compiling
- [x] fresh checkout can be compiled

This is just a reminder, I will close this ticket. Please add a comment in case something is missing or you finished your work.
